### PR TITLE
Fix for full platform build

### PR DESCRIPTION
**Pull request by SHtress**

### CODE REVIEW

**Review by MksmOrlov — COMMENTED** [review]
How to install sc-machine using ostis-web-platform? Should we use prepare.sh script? It will install sc-web

**Comment by SHtress** [comment]
Yes, you use prepare.sh.
What errors? Provide description or screenshots.

**Review by smousy — APPROVED** [review]

**Comment by MksmOrlov** [comment]
> Yes, you use prepare.sh. What errors? Provide description or screenshots.

image
image
image

**Comment by SHtress** [comment]
> > Yes, you use prepare.sh. What errors? Provide description or screenshots.
> 
> image image image

Strange, @smousy can you try to install platform and check if you have same error? Looks like it can't build sc-machine, but not the part with sc-component-manager.

**Pull request merged**
